services:
  app:
    image: feloraf/felora
    container_name: felora
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - ${PORT:-9501}:${PORT:-9501}
    volumes:
      - .:/var/www/felora
