services:
  app:
    image: mqtt-auth/swoole
    container_name: mqtt-auth
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    ports:
      - ${PORT:-9501}:${PORT:-9501}
    volumes:
      - ..:/var/www/mqtt-auth